// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8H1jGg2pLe03IE2wSOWAK_KEJbB4IAlw',
    appId: '1:296955372663:android:d7c682142a573e17449272',
    messagingSenderId: '296955372663',
    projectId: 'azkar-4a907',
    storageBucket: 'azkar-4a907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-EK9DwGui9UvGS5xqsj7W4tTu9KWR4GM',
    appId: '1:296955372663:ios:7da9f75471fbe50a449272',
    messagingSenderId: '296955372663',
    projectId: 'azkar-4a907',
    storageBucket: 'azkar-4a907.firebasestorage.app',
    androidClientId: '296955372663-aajtbkiirkfnuq3ff5kkjfqnl5trv643.apps.googleusercontent.com',
    iosClientId: '296955372663-76fa73nb8dpmhbaip28unh3faau59fg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.azkarAdmin',
  );
}
